homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.0000
  longitude: 105.0628
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1522
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  # Customization file
  customize: "!include customize.yaml"
